var help = [
  ['voiceButton', 'This is an additive synth with harmonics changing their volume over time. Click the <b>voice button</b> to edit the sound.<br/><i class="material-icons">graphic_eq</i>'],
  ['onoffButton', 'Click the <b>note button</b> to switch the audio on and off, if you made changes to the spectrum, or if there is <i>no sound</i>.<br/><i class="material-icons">music_note</i><i class="material-icons">music_off</i>'],
  ['keyboard', 'Touch and slide or click and move cursor vertically on the <b>multitouch surface</b>, or use <b>MIDI</b> or standard keyboard.<br/><i class="material-icons">border_inner</i>'],
  ['scroll', '<b>Scroll</b> along or across the playing surface, one semitone at a time. It is two octaves long and one octave high.<br/><i class="material-icons">arrow_drop_up</i><i class="material-icons">arrow_drop_down</i><i class="material-icons">arrow_left</i><i class="material-icons">arrow_right</i>'],
  ['spectrum', 'Slide vertically or click on the <b>harmonic levels</b> or horizontally and vertically on their <b>volume gradients</b> to change values.<br/><i class="material-icons">bar_chart</i><i class="material-icons">filter_list</i>'],
  ['h_select', 'To edit them from keyboard, press a key while holding <b>Shift</b>. Values go up from upper left side of it to lower right.<br/><i class="material-icons">bar_chart</i><i class="material-icons">filter_list</i><i class="material-icons">keyboard</i>'],
  ['time', 'Scroll the <b>time slider</b> or click the <b>scroll buttons</b> to switch in time to different points of your sound.<br/><i class="material-icons">arrow_right_alt</i><i class="material-icons">arrow_drop_up</i><i class="material-icons">arrow_drop_down</i>'],
  ['h_select', 'Or with the keyboard, select a harmonic with <b>Left and Right Arrow keys</b> and a point in time with <b>Up and Down Arrow</b>.<br/><i class="material-icons">arrow_right_alt</i><i class="material-icons">arrow_drop_down</i><i class="material-icons">keyboard</i>'],
  ['add', 'Add new or remove selected time points with <b>control point buttons</b>. New point will appear before the current one.<br/><i class="material-icons">add_circle_outline</i><i class="material-icons">remove_circle_outline</i>'],
  ['timerButton', 'Scroll to any time point, start the <b>timer</b> and slide upon the vertical harmonic levels. They will change in realtime.<br/><i class="material-icons">timer</i><i class="material-icons">timer_off</i>'],
  ['download', 'Give your sound a name and <b>download</b> it, or <b>upload</b> the file back. It is a text file with small size and a <b>.csv</b> extension.<br/><i class="material-icons">get_app</i><i class="material-icons">publish</i>'],
  ['voice_add', 'If you want the synth to have multiple sounds, <b>add new voices</b> and <b>switch</b> among them.<br/><i class="material-icons">exposure_zero</i><i class="material-icons">arrow_drop_down</i>&nbsp;<i class="material-icons">queue</i>'],
  ['recButton', '<b>Record</b> your music or <b>stop</b> the recording and <b>play</b> it back. The <b>.wav</b> file will download automatically.<br/><i class="material-icons">fiber_manual_record</i><i class="material-icons">stop</i>&nbsp;<i class="material-icons">play_arrow</i><i class="material-icons">pause</i>'],
  ['scale', 'Change the <b>scale</b> of the playing surface to resemble a keyboard or stringed instrument like a guitar.<br/><i class="material-icons">straighten</i><i class="material-icons">line_weight</i>'],
  ['param', 'Change the audio parameters like <b>sample rate</b>, <b>MIDI input</b> or whether to show harmonic intervals on the playing surface.<br/><i class="material-icons">tune</i>'],
  ['help', 'Show or hide this <b>help</b> window.<br/><i class="material-icons">live_help</i>']
];